/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jay.student_management;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author JAYAPAL
 */
public class page27 extends javax.swing.JFrame {

    /**
     * Creates new form page27
     */
    
    int count=0;
    public page27() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jop1a = new javax.swing.JRadioButton();
        jop1b = new javax.swing.JRadioButton();
        jop1c = new javax.swing.JRadioButton();
        jop1d = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jop2a = new javax.swing.JRadioButton();
        jop2b = new javax.swing.JRadioButton();
        jop2c = new javax.swing.JRadioButton();
        jop2d = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jop3a = new javax.swing.JRadioButton();
        jop3b = new javax.swing.JRadioButton();
        jop3c = new javax.swing.JRadioButton();
        jop3d = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jop4a = new javax.swing.JRadioButton();
        jop4b = new javax.swing.JRadioButton();
        jop4c = new javax.swing.JRadioButton();
        jop4d = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jop5a = new javax.swing.JRadioButton();
        jop5b = new javax.swing.JRadioButton();
        jop5c = new javax.swing.JRadioButton();
        jop5d = new javax.swing.JRadioButton();
        jsubmit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jop6a = new javax.swing.JRadioButton();
        jop6b = new javax.swing.JRadioButton();
        jop6c = new javax.swing.JRadioButton();
        jop6d = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jop7a = new javax.swing.JRadioButton();
        jop7b = new javax.swing.JRadioButton();
        jop7c = new javax.swing.JRadioButton();
        jop7d = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jop8a = new javax.swing.JRadioButton();
        jop8b = new javax.swing.JRadioButton();
        jop8c = new javax.swing.JRadioButton();
        jop8d = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jop9a = new javax.swing.JRadioButton();
        jop9b = new javax.swing.JRadioButton();
        jop9c = new javax.swing.JRadioButton();
        jop9d = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jop10a = new javax.swing.JRadioButton();
        jop10b = new javax.swing.JRadioButton();
        jop10c = new javax.swing.JRadioButton();
        jop10d = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Assessment 1:");

        jLabel2.setText("1)How many types of varaibles in java?");

        buttonGroup1.add(jop1a);
        jop1a.setText("2");

        buttonGroup1.add(jop1b);
        jop1b.setText("3");
        jop1b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jop1bActionPerformed(evt);
            }
        });

        buttonGroup1.add(jop1c);
        jop1c.setText("7");
        jop1c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jop1cActionPerformed(evt);
            }
        });

        buttonGroup1.add(jop1d);
        jop1d.setText("4");

        jLabel3.setText("2) For specifies a single letter,what data type is used in java? ");

        buttonGroup2.add(jop2a);
        jop2a.setText("int");

        buttonGroup2.add(jop2b);
        jop2b.setText("float");

        buttonGroup2.add(jop2c);
        jop2c.setText("char");
        jop2c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jop2cActionPerformed(evt);
            }
        });

        buttonGroup2.add(jop2d);
        jop2d.setText("none of these");

        jLabel4.setText("3)The operator ?: denotes.");

        buttonGroup3.add(jop3a);
        jop3a.setText("arithmetic");
        jop3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jop3aActionPerformed(evt);
            }
        });

        buttonGroup3.add(jop3b);
        jop3b.setText("Ternary");
        jop3b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jop3bActionPerformed(evt);
            }
        });

        buttonGroup3.add(jop3c);
        jop3c.setText("unary");

        buttonGroup3.add(jop3d);
        jop3d.setText("logical");

        jLabel5.setText("4) To represent a decimal or fraction number, which data type is used?");

        buttonGroup4.add(jop4a);
        jop4a.setText("double");

        buttonGroup4.add(jop4b);
        jop4b.setText("float");

        buttonGroup4.add(jop4c);
        jop4c.setText("string");

        buttonGroup4.add(jop4d);
        jop4d.setText("int");

        jLabel6.setText("5) which type of variable is declared inside the main method and main class?");

        buttonGroup5.add(jop5a);
        jop5a.setText("local");

        buttonGroup5.add(jop5b);
        jop5b.setText("instance");

        buttonGroup5.add(jop5c);
        jop5c.setText("global");

        buttonGroup5.add(jop5d);
        jop5d.setText("static");

        jsubmit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jsubmit.setForeground(new java.awt.Color(0, 0, 255));
        jsubmit.setText("Submit");
        jsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsubmitActionPerformed(evt);
            }
        });

        jLabel7.setText("6) which one of the following is not a logical operator?");

        buttonGroup6.add(jop6a);
        jop6a.setText("AND");

        buttonGroup6.add(jop6b);
        jop6b.setText("OR");

        buttonGroup6.add(jop6c);
        jop6c.setText("NOT");

        buttonGroup6.add(jop6d);
        jop6d.setText("SHORT");

        jLabel8.setText("7) increment, decrement operator is termed as");

        buttonGroup7.add(jop7a);
        jop7a.setText("Uranary");

        buttonGroup7.add(jop7b);
        jop7b.setText("binary");

        buttonGroup7.add(jop7c);
        jop7c.setText("Ternary");

        buttonGroup7.add(jop7d);
        jop7d.setText("none above");

        jLabel9.setText("8) public class Demo{");

        jLabel10.setText("public static void main(String args[]){");

        jLabel11.setText("int a=5;");

        jLabel12.setText("System.out.println(a++);");

        jLabel13.setText("System.out.println(++a);");

        jLabel14.setText("}");

        jLabel15.setText("}");

        jLabel16.setText("what is the output of the above code?");

        buttonGroup8.add(jop8a);
        jop8a.setText("5,7");

        buttonGroup8.add(jop8b);
        jop8b.setText("6,8");
        jop8b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jop8bActionPerformed(evt);
            }
        });

        buttonGroup8.add(jop8c);
        jop8c.setText("6,7");

        buttonGroup8.add(jop8d);
        jop8d.setText("7,5");

        jLabel17.setText("9) which is prefix decrement operator?");

        buttonGroup9.add(jop9a);
        jop9a.setText("++a");

        buttonGroup9.add(jop9b);
        jop9b.setText("a--");

        buttonGroup9.add(jop9c);
        jop9c.setText("a++");

        buttonGroup9.add(jop9d);
        jop9d.setText("--a");

        jLabel18.setText("10) What is the default value of string data type?");

        buttonGroup10.add(jop10a);
        jop10a.setText("0");

        buttonGroup10.add(jop10b);
        jop10b.setText("NIL");

        buttonGroup10.add(jop10c);
        jop10c.setText("NULL");

        buttonGroup10.add(jop10d);
        jop10d.setText("none of these");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jop3a)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jop3b)
                                .addGap(18, 18, 18)
                                .addComponent(jop3c)
                                .addGap(18, 18, 18)
                                .addComponent(jop3d)
                                .addGap(74, 74, 74))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel16)
                                .addComponent(jLabel17)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addComponent(jop10a)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jop10b)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jop10c)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jop10d)
                                    .addGap(81, 81, 81)
                                    .addComponent(jsubmit))
                                .addComponent(jLabel6)
                                .addComponent(jLabel18)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(jop9a)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jop9b)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jop9c)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jop9d)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jop1a)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jop1b)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jop1c)
                        .addGap(18, 18, 18)
                        .addComponent(jop1d))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jop2a)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jop2b)
                        .addGap(18, 18, 18)
                        .addComponent(jop2c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jop2d))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jop4a)
                        .addGap(18, 18, 18)
                        .addComponent(jop4b)
                        .addGap(26, 26, 26)
                        .addComponent(jop4c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jop4d))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jop5a)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jop5b)
                        .addGap(18, 18, 18)
                        .addComponent(jop5c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jop5d))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jop6a)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jop6b)
                        .addGap(18, 18, 18)
                        .addComponent(jop6c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jop6d))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jop7a)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jop7b)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jop7c)
                        .addGap(18, 18, 18)
                        .addComponent(jop7d))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jop8b)
                            .addComponent(jop8a)
                            .addComponent(jop8c)
                            .addComponent(jop8d))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jop1a)
                    .addComponent(jop1b)
                    .addComponent(jop1c)
                    .addComponent(jop1d))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jop2a)
                    .addComponent(jop2b)
                    .addComponent(jop2c)
                    .addComponent(jop2d))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jop3a)
                    .addComponent(jop3b)
                    .addComponent(jop3c)
                    .addComponent(jop3d))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jop4a)
                    .addComponent(jop4b)
                    .addComponent(jop4c)
                    .addComponent(jop4d))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jop5a)
                    .addComponent(jop5b)
                    .addComponent(jop5c)
                    .addComponent(jop5d))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jop6a)
                    .addComponent(jop6b)
                    .addComponent(jop6c)
                    .addComponent(jop6d))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jop7a)
                    .addComponent(jop7b)
                    .addComponent(jop7c)
                    .addComponent(jop7d))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jop8a))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jop8b))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jop8c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jop8d)
                            .addComponent(jLabel13))
                        .addGap(13, 13, 13)))
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jop9a)
                    .addComponent(jop9b)
                    .addComponent(jop9c)
                    .addComponent(jop9d))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jop10a)
                    .addComponent(jop10b)
                    .addComponent(jop10c)
                    .addComponent(jop10d)
                    .addComponent(jsubmit))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jop1bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jop1bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jop1bActionPerformed

    private void jop1cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jop1cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jop1cActionPerformed

    private void jop2cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jop2cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jop2cActionPerformed

    private void jop3bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jop3bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jop3bActionPerformed

    private void jop3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jop3aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jop3aActionPerformed

    private void jsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsubmitActionPerformed
        // TODO add your handling code here:
        if((!jop1a.isSelected())&&(!jop1b.isSelected())&&(!jop1c.isSelected())&&(!jop1d.isSelected())){
            JOptionPane.showMessageDialog(null,"Please select the answer for question 1");
        }
        else if((!jop2a.isSelected())&&(!jop2b.isSelected())&&(!jop2c.isSelected())&&(!jop2d.isSelected())){
            JOptionPane.showMessageDialog(null,"Please select the answer for question 2");
        }
        else if((!jop3a.isSelected())&&(!jop3b.isSelected())&&(!jop3c.isSelected())&&(!jop3d.isSelected())){
            JOptionPane.showMessageDialog(null,"Please select the answer for question 3");
        }
        else if((!jop4a.isSelected())&&(!jop4b.isSelected())&&(!jop4c.isSelected())&&(!jop4d.isSelected())){
            JOptionPane.showMessageDialog(null,"Please select the answer for question 4");
        }
        else if((!jop5a.isSelected())&&(!jop5b.isSelected())&&(!jop5c.isSelected())&&(!jop5d.isSelected())){
            JOptionPane.showMessageDialog(null,"Please select the answer for question 5");
        }
        else if((!jop6a.isSelected())&&(!jop6b.isSelected())&&(!jop6c.isSelected())&&(!jop6d.isSelected())){
            JOptionPane.showMessageDialog(null,"Please select the answer for question 6");
        }
        else if((!jop7a.isSelected())&&(!jop7b.isSelected())&&(!jop7c.isSelected())&&(!jop7d.isSelected())){
            JOptionPane.showMessageDialog(null,"Please select the answer for question 7");
        }
        else if((!jop8a.isSelected())&&(!jop8b.isSelected())&&(!jop8c.isSelected())&&(!jop8d.isSelected())){
            JOptionPane.showMessageDialog(null,"Please select the answer for question 8");
        }
        else if((!jop9a.isSelected())&&(!jop9b.isSelected())&&(!jop9c.isSelected())&&(!jop9d.isSelected())){
            JOptionPane.showMessageDialog(null,"Please select the answer for question 9");
        }
        else if((!jop10a.isSelected())&&(!jop10b.isSelected())&&(!jop10c.isSelected())&&(!jop10d.isSelected())){
            JOptionPane.showMessageDialog(null,"Please select the answer for question 10");
        }
        else{
            if(jop1b.isSelected()){
                count++;
            }
            if(jop2c.isSelected()){
                count++;
            }
            if(jop3b.isSelected()){
                count++;
            }
            if(jop4b.isSelected()){
                count++;
            }
            if(jop5a.isSelected()){
                count++;
            }
            if(jop6d.isSelected()){
                count++;
            }
            if(jop7a.isSelected()){
                count++;
            }
            if(jop8a.isSelected()){
                count++;
            }
            if(jop9d.isSelected()){
                count++;
            }
            if(jop10c.isSelected()){
                count++;
            }
            JOptionPane.showMessageDialog(null,"Successfully submitted");
            JOptionPane.showMessageDialog(null,"Your Score is "+count);
            JOptionPane.showMessageDialog(null,"let us see the Answers");
            page28 p28=new page28();
            p28.show();
            
            
            //jsubmit.setVisible(false);
            //jfinish.setVisible(true);
            //jfinish.setText("Finish");
            //jsubmit.setForeground(Color.green);
            //page26 p26=new page26();
            //p26.show();
            //jsubmit.setVisible(false);
            //jsee.setVisible(true);
            
        }
    }//GEN-LAST:event_jsubmitActionPerformed

    private void jop8bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jop8bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jop8bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(page27.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(page27.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(page27.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(page27.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new page27().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jop10a;
    private javax.swing.JRadioButton jop10b;
    private javax.swing.JRadioButton jop10c;
    private javax.swing.JRadioButton jop10d;
    private javax.swing.JRadioButton jop1a;
    private javax.swing.JRadioButton jop1b;
    private javax.swing.JRadioButton jop1c;
    private javax.swing.JRadioButton jop1d;
    private javax.swing.JRadioButton jop2a;
    private javax.swing.JRadioButton jop2b;
    private javax.swing.JRadioButton jop2c;
    private javax.swing.JRadioButton jop2d;
    private javax.swing.JRadioButton jop3a;
    private javax.swing.JRadioButton jop3b;
    private javax.swing.JRadioButton jop3c;
    private javax.swing.JRadioButton jop3d;
    private javax.swing.JRadioButton jop4a;
    private javax.swing.JRadioButton jop4b;
    private javax.swing.JRadioButton jop4c;
    private javax.swing.JRadioButton jop4d;
    private javax.swing.JRadioButton jop5a;
    private javax.swing.JRadioButton jop5b;
    private javax.swing.JRadioButton jop5c;
    private javax.swing.JRadioButton jop5d;
    private javax.swing.JRadioButton jop6a;
    private javax.swing.JRadioButton jop6b;
    private javax.swing.JRadioButton jop6c;
    private javax.swing.JRadioButton jop6d;
    private javax.swing.JRadioButton jop7a;
    private javax.swing.JRadioButton jop7b;
    private javax.swing.JRadioButton jop7c;
    private javax.swing.JRadioButton jop7d;
    private javax.swing.JRadioButton jop8a;
    private javax.swing.JRadioButton jop8b;
    private javax.swing.JRadioButton jop8c;
    private javax.swing.JRadioButton jop8d;
    private javax.swing.JRadioButton jop9a;
    private javax.swing.JRadioButton jop9b;
    private javax.swing.JRadioButton jop9c;
    private javax.swing.JRadioButton jop9d;
    private javax.swing.JButton jsubmit;
    // End of variables declaration//GEN-END:variables
}
